### ISSUE TITLE
Prefix for terraform

### ISSUE THREAD

**Issue by bernardo-bruning** [cloudspannerecosystem/autoscaler#33]
Hi!

First of all, this repository is great and can be help me. Today I work into in project shared into my company, and to create a new resource ever need declare an team prefix, however the autoscaler don't provide this into your terraform configs.

So, would it be possible to provide an prefix variable for terraform? If the answer is yes, I can pull this implementation and send a PR.

**Comment by davidcueva** [comment]
Hi Bernardo, 
we discussed about your suggestion, and want to understand your use case better.

Would it be possible for you to have separate projects instead of using a prefix to differentiate between resources within the same project?
Having one project per application per environment is one of Google's recommendations in our [best practices for enterprise organizations](https://cloud.google.com/docs/enterprise/best-practices-for-enterprise-organizations#project-structure).

We are a bit worried that adding a prefix means possibly copy pasting the same snippet over and over throughout all the resources in the Autoscaler, or coming up with some other way of generating the resource names with a prefix.

**Comment by bernardo-bruning** [comment]
Hi @davidcueva!

> Would it be possible for you to have separate projects instead of using a prefix to differentiate between resources within the same project?

It's possible. I will communicate with an infrastructure team to provide a new project for Autoescaler.

> We are a bit worried that adding a prefix means possibly copy pasting the same snippet over and over throughout all the resources in the Autoscaler, or coming up with some other way of adding the prefix to the resource names.

My first approach was to include the field to define the prefix in the terraform. I agree to separate projects

**Comment by davidcueva** [comment]
Awesome ! Thanks Bernardo. 
Since you are looking into having separate projects I will close this issue for now, but feel free to reopen if you run into issues.
