### ISSUE TITLE
Best practice scaling metrics using MAX?

### ISSUE THREAD

**Issue by alexlo03** [cloudspannerecosystem/autoscaler#345]
Hello,

Out of the box this project uses, if I am reading it correctly, [the maximum CPU value it sees over a 60s period](https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/poller/poller-core/index.js#L90-L102). Is this recommended? It seems a bit spiky in practice. Would moving to ALIGN_PERCENTILE_95 instead of ALIGN_MAX be recommended or contraindicated?

**Comment by davidcueva** [comment]
hi Alex,

We have not had reports so far about spikiness because of using `ALIGN_MAX `, but that may be a side-effect of using a margin which smooths out the spikes. 
I cannot say for sure if `ALIGN_PERCENTILE_95` might be better, but I'm happy to hear your feedback, if you'd like to test it. 

Feel free to reopen this thread if you want to report back.

David
