### ISSUE TITLE
Poller function encounters javascript error

### ISSUE THREAD

**Issue by ponkumarm** [cloudspannerecosystem/autoscaler#52]
Poller function fails with below error

`{
insertId: "000000-c7f61764-5b66-477e-8c8e-2448fc1cddff"
jsonPayload: {
message: "An error occurred in the Autoscaler poller function
TypeError: spanners is not iterable
    at checkSpanners (/workspace/index.js:348:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async exports.checkSpannerScaleMetricsPubSub (/workspace/index.js:360:5)"
payload: {
}
}
labels: {
execution_id: "e9blyz99v02m"
}
logName: "****"
receiveTimestamp: "2021-10-19T04:47:20.303390670Z"
resource: {
labels: {
function_name: "tf-poller-function"
project_id: "****"
region: "****"
}
type: "cloud_function"
}
severity: "ERROR"
timestamp: "2021-10-19T04:47:09.633Z"
trace: "projects/*****"
}`

**Comment by bgood** [comment]
@ponkumarm I was able to reproduce a similar error, by removing the `[ ]` in the configuration. The configuration is structured as an array of JSON objects, so that it can support multiple Cloud Spanners in Cloud Scheduler job.  Please check your config to see if you are missing the square brackets issue.

**Comment by ponkumarm** [comment]
Thanks @bgood for checking in and responding back.

I do include [ ] in my payload and here is how my configuration looks like:

```
[
    {
        "projectId": "***",
        "instanceId": "****",
        "scalerPubSubTopic": "***",
        "units": "NODES",
        "minSize": 1,
        "maxSize": 4,
        "stepSize": 1,
        "overloadStepSize": 2,
        "scaleInCoolingMinutes":1,
        "scaleOutCoolingMinutes":1
    }
]
```

I could notice something strange in the log message as below:

```
{
resource: {
labels: {3}
type: "cloud_function"
}
severity: "INFO"
textPayload: "**_----- undefined/undefined: Getting Metrics -----_**" <-- Its not getting values from spanner object
timestamp: "2021-10-22T01:27:54.783Z"
}
```

And this is the final error message:

```
An error occurred in the Autoscaler poller function
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getMetrics (/workspace/index.js:312:31)
    at checkSpanners (/workspace/index.js:349:25)
    at async exports.checkSpannerScaleMetricsPubSub (/workspace/index.js:360:5)
```

Am I missing anything here?

**Comment by bgood** [comment]
This issue is pretty stale, so closing feel free to reopen if needed.

As a side note for posterity, the `exports.checkSpannerScaleMetricsHTTP` endpoint in the poller-core exposes an HTTP endpoint which is useful for testing. In that endpoint you can set the payload JSON that would be delivered PubSub. That allows you to set the configuration and connect a debugger to the node process and use a browser to trigger the execution of the poller, so you can debug and set breakpoints.
